param(
    [Parameter(Mandatory = $true)]
    [int]$IssueNumber,

    [Parameter(Mandatory = $true)]
    [string]$Repository,

    [Parameter(Mandatory = $true)]
    [string]$BaseBranch,

    [Parameter(Mandatory = $true)]
    [string]$RunId
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot "ai-worker-common.ps1")

Test-RequiredCommand "git"
Test-RequiredCommand "gh"
Test-RequiredCommand "claude"

$model = if ($env:AI_CLAUDE_MODEL) { $env:AI_CLAUDE_MODEL } else { "sonnet" }
$budget = if ($env:AI_CLAUDE_MAX_BUDGET_USD) { $env:AI_CLAUDE_MAX_BUDGET_USD } else { "2" }

$issue = gh issue view $IssueNumber --repo $Repository --json number,title,body,url | ConvertFrom-Json
$slug = ConvertTo-Slug -Value $issue.title
$branchName = "ai-coding/issue-$IssueNumber-$slug-$RunId"

Initialize-FreshBranch -BranchName $branchName -BaseBranch $BaseBranch

$prompt = @"
You are the CODING agent in a specialized worker pipeline (separate agents exist for
unit tests, e2e tests, and review — do not do their job, stay scoped to implementation).
Running locally through a GitHub self-hosted runner (Windows).

Source GitHub issue:
- Repository: $Repository
- Issue: #$($issue.number)
- URL: $($issue.url)
- Title: $($issue.title)

Issue body:
~~~markdown
$($issue.body)
~~~

Task:
1. Implement the requested code change in this repository, scoped to the issue.
2. You MAY add minimal smoke-level tests if a function is otherwise untestable, but
   comprehensive unit/e2e test coverage is a SEPARATE worker's job — do not over-invest there.
3. Do not merge, do not push, and do not create a pull request — the wrapper script handles that.
4. Do not read or print secrets. Avoid destructive git commands.
5. Before finishing, leave the workspace ready to commit (diff applied on disk).

Output: short summary of changed files and what each change does.
"@

$promptPath = "ai-coding-runs/issue-$IssueNumber-coding-prompt.md"
Write-Utf8File -Path $promptPath -Content $prompt

$allowedTools = "Read,Edit,Write,Glob,Grep,LS,Bash(git status:*),Bash(git diff:*),Bash(python:*),Bash(pytest:*)"
$result = Invoke-ClaudeCode -Prompt $prompt -Model $model -Budget $budget -AllowedTools $allowedTools

if ($result.ExitCode -ne 0) {
    $excerpt = if ($result.Text.Length -gt 3000) { $result.Text.Substring(0, 3000) + "`n... truncated ..." } else { $result.Text }
    gh issue comment $IssueNumber --repo $Repository --body "CodingWorker failed (exit $($result.ExitCode)). Run: $env:GITHUB_SERVER_URL/$Repository/actions/runs/$RunId`n`n``````text`n$excerpt`n``````"
    throw "Claude Code exited with code $($result.ExitCode)."
}

$pushed = Push-WorkerChanges -CommitMessage "AI(coding): implement issue #$IssueNumber" -BranchName $branchName -SetUpstream
if (-not $pushed) {
    gh issue comment $IssueNumber --repo $Repository --body "CodingWorker finished but produced no file changes. Run: $env:GITHUB_SERVER_URL/$Repository/actions/runs/$RunId"
    throw "Claude Code produced no file changes."
}

$body = "Relates to #$IssueNumber`n`nAuto-generated by CodingWorker (model: $model).`n`n``````text`n$($result.Text)`n``````"
$bodyPath = ".ai-coding-pr-body.md"
Write-Utf8File -Path $bodyPath -Content $body
$prUrl = gh pr create --repo $Repository --title "AI: $($issue.title)" --body-file $bodyPath --head $branchName --base $BaseBranch
if ($LASTEXITCODE -ne 0) { throw "Failed to create pull request." }

gh label create "ai-coding-done" --repo $Repository --color "0e8a16" --description "AI coding worker completed" 2>$null | Out-Null
Invoke-Checked "gh" "issue" "edit" "$IssueNumber" "--repo" $Repository "--remove-label" "ai-coding-task" "--add-label" "ai-coding-done"
Invoke-Checked "gh" "issue" "comment" "$IssueNumber" "--repo" $Repository "--body" "CodingWorker opened pull request: $prUrl"

Write-Output "Opened pull request: $prUrl"
