param(
    [Parameter(Mandatory = $true)]
    [string]$JiraKey,

    [Parameter(Mandatory = $true)]
    [string]$Repository,

    [Parameter(Mandatory = $true)]
    [string]$BaseBranch,

    [Parameter(Mandatory = $true)]
    [string]$RunId
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot "ai-worker-common.ps1")

Test-RequiredCommand "git"
Test-RequiredCommand "gh"
Test-RequiredCommand "claude"

$model = if ($env:AI_CLAUDE_MODEL) { $env:AI_CLAUDE_MODEL } else { "sonnet" }
$budget = if ($env:AI_CLAUDE_MAX_BUDGET_USD) { $env:AI_CLAUDE_MAX_BUDGET_USD } else { "2" }
$taskTitle = $env:TASK_TITLE
$taskBody = $env:TASK_BODY

if ([string]::IsNullOrWhiteSpace($taskTitle)) { throw "TASK_TITLE env var is required (set by the workflow from Jira dispatch payload)." }

# No GitHub issue is created for this task — Jira ($JiraKey) is the single source of truth.
# The worker only produces a branch + PR; the PR body links back to the Jira key.
$slug = ConvertTo-Slug -Value $taskTitle
$branchName = "ai-coding/$($JiraKey.ToLowerInvariant())-$slug-$RunId"

Initialize-FreshBranch -BranchName $branchName -BaseBranch $BaseBranch

$prompt = @"
You are the CODING agent in a specialized worker pipeline (separate agents exist for
unit tests, e2e tests, and review — do not do their job, stay scoped to implementation).
Running locally through a GitHub self-hosted runner (Windows).

Source of truth: Jira issue $JiraKey (this task has NO corresponding GitHub issue —
Jira is the only tracker; do not create or reference a GitHub issue).

Task title: $taskTitle

Task description:
~~~markdown
$taskBody
~~~

Task:
1. Implement the requested code change in this repository, scoped to the task above.
2. You MAY add minimal smoke-level tests if a function is otherwise untestable, but
   comprehensive unit/e2e test coverage is a SEPARATE worker's job — do not over-invest there.
3. Do not merge, do not push, and do not create a pull request — the wrapper script handles that.
4. Do not read or print secrets. Avoid destructive git commands.
5. Before finishing, leave the workspace ready to commit (diff applied on disk).

Output: short summary of changed files and what each change does.
"@

$promptPath = "ai-coding-runs/$($JiraKey.ToLowerInvariant())-coding-prompt.md"
Write-Utf8File -Path $promptPath -Content $prompt

$allowedTools = "Read,Edit,Write,Glob,Grep,LS,Bash(git status:*),Bash(git diff:*),Bash(dotnet build:*),Bash(dotnet test:*),Bash(dotnet restore:*)"
$result = Invoke-ClaudeCode -Prompt $prompt -Model $model -Budget $budget -AllowedTools $allowedTools

if ($result.ExitCode -ne 0) {
    Write-Error "CodingWorker failed (exit $($result.ExitCode)) for $JiraKey. Run: $env:GITHUB_SERVER_URL/$Repository/actions/runs/$RunId"
    throw "Claude Code exited with code $($result.ExitCode)."
}

$pushed = Push-WorkerChanges -CommitMessage "AI(coding): $JiraKey $taskTitle" -BranchName $branchName -SetUpstream
if (-not $pushed) {
    throw "Claude Code produced no file changes for $JiraKey."
}

$body = "Source: Jira **$JiraKey** — $taskTitle`n`nAuto-generated by CodingWorker (model: $model). No GitHub issue exists for this task; Jira is the source of truth.`n`n``````text`n$($result.Text)`n``````"
$bodyPath = ".ai-coding-pr-body.md"
Write-Utf8File -Path $bodyPath -Content $body
$prUrl = gh pr create --repo $Repository --title "AI: [$JiraKey] $taskTitle" --body-file $bodyPath --head $branchName --base $BaseBranch
if ($LASTEXITCODE -ne 0) { throw "Failed to create pull request." }

Write-Output "JIRA_KEY=$JiraKey"
Write-Output "PR_URL=$prUrl"
Write-Output "Opened pull request: $prUrl"
