// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyPlatform.Infrastructure.Persistence;

#nullable disable

namespace PolicyPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(PolicyPlatformDbContext))]
    partial class PolicyPlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PolicyPlatform.Domain.Claims.Claim", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Channel")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("IncidentDate")
                    .HasColumnType("TEXT");

                b.Property<Guid>("PolicyId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("PolicyId");

                b.ToTable("Claims");
            });
#pragma warning restore 612, 618
        }
    }
}
