// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyPlatform.Infrastructure.Persistence;

#nullable disable

namespace PolicyPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PolicyPlatformDbContext))]
    [Migration("20260719120000_AddLoginHistoryEntries")]
    partial class AddLoginHistoryEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyPlatform.Domain.Auth.LoginHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_label");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("device_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OsName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("os_name");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("os_version");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "OccurredAt" })
                        .HasDatabaseName("IX_login_history_entries_user_id_occurred_at")
                        .IsDescending(false, true);

                    b.ToTable("login_history_entries");
                });

            modelBuilder.Entity("PolicyPlatform.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PolicyPlatform.Domain.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("PolicyPlatform.Domain.Policies.Policy", b =>
                {
                    b.OwnsMany("PolicyPlatform.Domain.Policies.Coverage", "Coverages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("PolicyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("PolicyId");

                            b1.ToTable("Coverage");

                            b1.WithOwner()
                                .HasForeignKey("PolicyId");

                            b1.OwnsOne("PolicyPlatform.Domain.Policies.Money", "Premium", b2 =>
                                {
                                    b2.Property<int>("CoverageId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PremiumAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("PremiumCurrency");

                                    b2.HasKey("CoverageId");

                                    b2.ToTable("Coverage");

                                    b2.WithOwner()
                                        .HasForeignKey("CoverageId");
                                });

                            b1.OwnsOne("PolicyPlatform.Domain.Policies.Money", "SumInsured", b2 =>
                                {
                                    b2.Property<int>("CoverageId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("SumInsuredAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("SumInsuredCurrency");

                                    b2.HasKey("CoverageId");

                                    b2.ToTable("Coverage");

                                    b2.WithOwner()
                                        .HasForeignKey("CoverageId");
                                });

                            b1.Navigation("Premium")
                                .IsRequired();

                            b1.Navigation("SumInsured")
                                .IsRequired();
                        });

                    b.Navigation("Coverages");
                });
#pragma warning restore 612, 618
        }
    }
}
